<?php

class webFullConceptTableSeeder extends Seeder {
    public function run()
    {
        
        DB::table('proyecto_comentario_status')->insert(array(
                    
            array(
                'id' => 0,
                'nombre' => 'Pendiente',
                'ordering' => 1,
            ),

            array(
                'id' => 1,
                'nombre' => 'Aprobado',
                'ordering' => 2,
            ),

            array(
                'id' => 2,
                'nombre' => 'No Aprobado',
                'ordering' => 3,
            ),

        ));
        DB::table('proyecto_comentarios')->insert(array(
                    
            array(
                'id' => 43,
                'proyecto_id' => 4,
                'comentario' => 'segundo com para proyecto 4',
                'nombre' => 'cdscdsd',
                'stars' => 5,
                'created_at' => '2014-07-04 16:55:22',
                'updated_at' => '2014-07-07 10:08:31',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 42,
                'proyecto_id' => 4,
                'comentario' => 'primer comentari opara proyecto 4',
                'nombre' => 'soy el número 4',
                'stars' => 4,
                'created_at' => '2014-07-04 16:51:45',
                'updated_at' => '2014-07-07 10:05:42',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 0,
            ),

            array(
                'id' => 4,
                'proyecto_id' => 1,
                'comentario' => 'comentario testing 4',
                'nombre' => '',
                'stars' => 5,
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 5,
                'proyecto_id' => 1,
                'comentario' => 'comentario testing 5',
                'nombre' => '',
                'stars' => 2,
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 6,
                'proyecto_id' => 1,
                'comentario' => 'comentario testing 6',
                'nombre' => '',
                'stars' => 3,
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 7,
                'proyecto_id' => 1,
                'comentario' => 'comentario testing 7',
                'nombre' => '',
                'stars' => 1,
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 8,
                'proyecto_id' => 1,
                'comentario' => 'comentario testing 8',
                'nombre' => '',
                'stars' => 2,
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 9,
                'proyecto_id' => 1,
                'comentario' => 'comentario testing 9',
                'nombre' => '',
                'stars' => 5,
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 10,
                'proyecto_id' => 1,
                'comentario' => 'comentario testing 10',
                'nombre' => '',
                'stars' => 5,
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 11,
                'proyecto_id' => 1,
                'comentario' => 'comentario testing 11',
                'nombre' => '',
                'stars' => 2,
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 12,
                'proyecto_id' => 1,
                'comentario' => 'comentario testing 12',
                'nombre' => '',
                'stars' => 1,
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 13,
                'proyecto_id' => 1,
                'comentario' => 'comentario testing 13',
                'nombre' => '',
                'stars' => 4,
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 14,
                'proyecto_id' => 1,
                'comentario' => 'comentario testing 14',
                'nombre' => '',
                'stars' => 5,
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 15,
                'proyecto_id' => 1,
                'comentario' => 'comentario testing 15',
                'nombre' => '',
                'stars' => 2,
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 16,
                'proyecto_id' => 2,
                'comentario' => 'comentario testing',
                'nombre' => '',
                'stars' => 2,
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 17,
                'proyecto_id' => 2,
                'comentario' => 'comentario testing 2',
                'nombre' => '',
                'stars' => 3,
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 18,
                'proyecto_id' => 2,
                'comentario' => 'comentario testing 3',
                'nombre' => '',
                'stars' => 1,
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 19,
                'proyecto_id' => 2,
                'comentario' => 'comentario testing 4',
                'nombre' => '',
                'stars' => 5,
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 20,
                'proyecto_id' => 2,
                'comentario' => 'comentario testing 5',
                'nombre' => '',
                'stars' => 2,
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 21,
                'proyecto_id' => 2,
                'comentario' => 'comentario testing 6',
                'nombre' => '',
                'stars' => 3,
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 22,
                'proyecto_id' => 2,
                'comentario' => 'comentario testing 7',
                'nombre' => '',
                'stars' => 1,
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 23,
                'proyecto_id' => 2,
                'comentario' => 'comentario testing 8',
                'nombre' => '',
                'stars' => 2,
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 24,
                'proyecto_id' => 2,
                'comentario' => 'comentario testing 9',
                'nombre' => '',
                'stars' => 5,
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 25,
                'proyecto_id' => 2,
                'comentario' => 'comentario testing 10',
                'nombre' => '',
                'stars' => 5,
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-07 10:00:27',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 0,
            ),

            array(
                'id' => 26,
                'proyecto_id' => 2,
                'comentario' => 'comentario testing 11',
                'nombre' => '',
                'stars' => 2,
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 27,
                'proyecto_id' => 2,
                'comentario' => 'comentario testing 12',
                'nombre' => '',
                'stars' => 1,
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 28,
                'proyecto_id' => 2,
                'comentario' => 'comentario testing 13',
                'nombre' => '',
                'stars' => 4,
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 29,
                'proyecto_id' => 2,
                'comentario' => 'comentario testing 14',
                'nombre' => '',
                'stars' => 5,
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 30,
                'proyecto_id' => 2,
                'comentario' => 'comentario testing 15',
                'nombre' => '',
                'stars' => 2,
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 31,
                'proyecto_id' => 2,
                'comentario' => '&lt;a href=&quot;comentario 1666666666666&quot;&gt;comentario 1666666666666&lt;/a&gt;',
                'nombre' => 'don cuau',
                'stars' => 1,
                'created_at' => '2014-07-02 17:43:59',
                'updated_at' => '2014-07-02 17:43:59',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 32,
                'proyecto_id' => 2,
                'comentario' => 'comentario 17',
                'nombre' => 'Señoron Don Cuau',
                'stars' => 1,
                'created_at' => '2014-07-02 17:46:48',
                'updated_at' => '2014-07-02 17:46:48',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 33,
                'proyecto_id' => 2,
                'comentario' => 'cvdfvdf 18',
                'nombre' => 'hola18',
                'stars' => 1,
                'created_at' => '2014-07-02 17:51:52',
                'updated_at' => '2014-07-02 17:51:52',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 34,
                'proyecto_id' => 2,
                'comentario' => 'hola 19',
                'nombre' => 'cdscvdscvd',
                'stars' => 1,
                'created_at' => '2014-07-02 18:00:25',
                'updated_at' => '2014-07-02 18:00:25',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 1,
            ),

            array(
                'id' => 35,
                'proyecto_id' => 2,
                'comentario' => 'com 20',
                'nombre' => 'com 20',
                'stars' => 1,
                'created_at' => '2014-07-02 18:03:11',
                'updated_at' => '2014-07-07 10:08:22',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 0,
            ),

            array(
                'id' => 36,
                'proyecto_id' => 2,
                'comentario' => 'mis ocmentarios d eprueba que tal wiiii, mis ocmentarios d eprueba que tal wiiii, mis ocmentarios d eprueba que tal wiiii, mis ocmentarios d eprueba que tal wiiii, mis ocmentarios d eprueba que tal wiiii, mis ocmentarios d eprueba que tal wiiii, mis ocmentarios d eprueba que tal wiiii, ',
                'nombre' => 'Señoron don cuau',
                'stars' => 1,
                'created_at' => '2014-07-02 18:04:44',
                'updated_at' => '2014-07-07 10:08:16',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 0,
            ),

            array(
                'id' => 37,
                'proyecto_id' => 2,
                'comentario' => 'mis ocmentarios d eprueba que tal wiiii, mis ocmentarios d eprueba que tal wiiii, mis ocmentarios d eprueba que tal wiiii, mis ocmentarios d eprueba que tal wiiii, mis ocmentarios d eprueba que tal wiiii, mis ocmentarios d eprueba que tal wiiii, mis ocmentarios d eprueba que tal wiiii, ',
                'nombre' => 'Señoron don cuau',
                'stars' => 1,
                'created_at' => '2014-07-03 08:31:51',
                'updated_at' => '2014-07-07 10:07:56',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
                'status_id' => 0,
            ),

        ));
        DB::table('proyecto_imagenes')->insert(array(
                    
            array(
                'id' => 9,
                'proyecto_id' => 1,
                'archivo' => 'proy-2.jpg',
                'logo' => 'logo_mlc.png',
                'created_at' => '2014-07-04 12:18:20',
                'updated_at' => '2014-07-04 12:18:21',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 19,
                'proyecto_id' => 1,
                'archivo' => 'proy-6.jpg',
                'logo' => 'logo_mlc.png',
                'created_at' => '2014-07-04 13:00:31',
                'updated_at' => '2014-07-04 13:00:31',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 3,
                'proyecto_id' => 1,
                'archivo' => 'proy-7.jpg',
                'logo' => 'logo_2501.png',
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 4,
                'proyecto_id' => 2,
                'archivo' => 'proy-4.jpg',
                'logo' => 'logo_marlo-v.png',
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 5,
                'proyecto_id' => 2,
                'archivo' => 'proy-3.jpg',
                'logo' => 'logo_marlo-otros.png',
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 6,
                'proyecto_id' => 2,
                'archivo' => 'proy-2.jpg',
                'logo' => 'logo_doce-loft.png',
                'created_at' => '2014-07-02 05:00:00',
                'updated_at' => '2014-07-02 05:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 11,
                'proyecto_id' => 1,
                'archivo' => 'proy-3.jpg',
                'logo' => 'logo_mlc.png',
                'created_at' => '2014-07-04 12:21:28',
                'updated_at' => '2014-07-04 12:21:28',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 16,
                'proyecto_id' => 1,
                'archivo' => 'proy-4.jpg',
                'logo' => 'logo_mlc.png',
                'created_at' => '2014-07-04 12:48:53',
                'updated_at' => '2014-07-04 12:48:53',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 20,
                'proyecto_id' => 5,
                'archivo' => 'proy-9.jpg',
                'logo' => 'logo_mlc.png',
                'created_at' => '2014-07-04 16:48:53',
                'updated_at' => '2014-07-04 16:48:53',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 21,
                'proyecto_id' => 4,
                'archivo' => 'proy-11.jpg',
                'logo' => 'logo_mlc.png',
                'created_at' => '2014-07-04 16:49:34',
                'updated_at' => '2014-07-04 16:49:34',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

        ));
        DB::table('proyecto_slideshow')->insert(array(
                    
            array(
                'id' => 1,
                'proyecto_id' => 1,
                'archivo' => 'projecto-main-img.jpg',
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-04 16:43:24',
                'ordering' => 3,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 2,
                'proyecto_id' => 1,
                'archivo' => 'projecto-main-img2.jpg',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '2014-07-04 16:43:24',
                'ordering' => 2,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 7,
                'proyecto_id' => 1,
                'archivo' => 'projecto-main-img.jpg',
                'created_at' => '2014-07-04 16:08:14',
                'updated_at' => '2014-07-04 16:43:24',
                'ordering' => 1,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 5,
                'proyecto_id' => 2,
                'archivo' => 'projecto-main-img2.jpg',
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 6,
                'proyecto_id' => 2,
                'archivo' => 'projecto-main-img.jpg',
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 8,
                'proyecto_id' => 1,
                'archivo' => 'projecto-main-img2.jpg',
                'created_at' => '2014-07-04 16:09:21',
                'updated_at' => '2014-07-04 16:43:24',
                'ordering' => 4,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 9,
                'proyecto_id' => 1,
                'archivo' => 'projecto-main-img.jpg',
                'created_at' => '2014-07-04 16:10:13',
                'updated_at' => '2014-07-04 16:43:24',
                'ordering' => 5,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 11,
                'proyecto_id' => 1,
                'archivo' => 'projecto-main-img2.jpg',
                'created_at' => '2014-07-04 16:12:48',
                'updated_at' => '2014-07-04 16:43:24',
                'ordering' => 6,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 13,
                'proyecto_id' => 5,
                'archivo' => 'projecto-main-img.jpg',
                'created_at' => '2014-07-04 16:48:40',
                'updated_at' => '2014-07-04 16:48:40',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 14,
                'proyecto_id' => 5,
                'archivo' => 'projecto-main-img2.jpg',
                'created_at' => '2014-07-04 16:48:44',
                'updated_at' => '2014-07-04 16:48:44',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 15,
                'proyecto_id' => 4,
                'archivo' => 'projecto-main-img2.jpg',
                'created_at' => '2014-07-04 16:49:49',
                'updated_at' => '2014-07-04 16:49:49',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

        ));
        DB::table('proyectos')->insert(array(
                    
            array(
                'id' => 1,
                'titulo' => 'TORRE EME',
                'concepto' => 'Proyecto exponencial, el cual proyectará el desarrollo cosmopolita y vanguardista del Puerto.',
                'descripcion' => 'Infraestructura imponente frente a una extensión de mar, que nos regala en su arquitectura el panorama más imponente de Mazatlán, la mejor vista; el mejor espacio. Torre M ofrece un estilo de vida incomparable y sofisticada en un residencial de alta calidad y estatus.',
                'logo' => 'torre-m-logo.png',
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 2,
                'titulo' => 'OTRO PROYECTO',
                'concepto' => 'Proyecto exponencial, el cual proyectará el desarrollo cosmopolita y vanguardista del Puerto.',
                'descripcion' => 'Infraestructura imponente frente a una extensión de mar, que nos regala en su arquitectura el panorama más imponente de Mazatlán, la mejor vista; el mejor espacio. Torre M ofrece un estilo de vida incomparable y sofisticada en un residencial de alta calidad y estatus.',
                'logo' => 'torre-m-logo.png',
                'created_at' => '2014-07-02 00:00:00',
                'updated_at' => '2014-07-02 00:00:00',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 3,
                'titulo' => 'Otro título',
                'concepto' => 'mi concepto',
                'descripcion' => 'mi descripción',
                'logo' => '',
                'created_at' => '2014-07-04 08:58:08',
                'updated_at' => '2014-07-04 08:58:08',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 4,
                'titulo' => 'Otro título',
                'concepto' => 'mi concepto',
                'descripcion' => 'mi descripción',
                'logo' => '',
                'created_at' => '2014-07-04 09:01:41',
                'updated_at' => '2014-07-04 09:01:41',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

            array(
                'id' => 5,
                'titulo' => 'Otro título',
                'concepto' => 'mi concepto',
                'descripcion' => 'mi descripción',
                'logo' => 'torre-m-logo.png',
                'created_at' => '2014-07-04 09:04:06',
                'updated_at' => '2014-07-04 09:04:06',
                'ordering' => 0,
                'published' => 1,
                'removed' => 0,
            ),

        ));
        DB::table('user_nivel_acceso')->insert(array(
                    
            array(
                'id' => 1,
                'tipo' => 'Administrador',
                'descripcion' => 'Nivel mas alto, puede hacer y deshacer',
                'published' => 1,
            ),

            array(
                'id' => 2,
                'tipo' => 'Fotógrafo',
                'descripcion' => 'Tiene ciertos privilegios, pero no todos',
                'published' => 1,
            ),

            array(
                'id' => 3,
                'tipo' => 'Distribuidor',
                'descripcion' => 'Tiene ciertos privilegios, pero no todos',
                'published' => 0,
            ),

            array(
                'id' => 4,
                'tipo' => 'Usuario Registrado',
                'descripcion' => 'casi no tienen privilegios',
                'published' => 0,
            ),

            array(
                'id' => 5,
                'tipo' => 'Público',
                'descripcion' => 'Nivel de permisos mas bajo que existe',
                'published' => 0,
            ),

            array(
                'id' => 6,
                'tipo' => 'Cliente Registrado',
                'descripcion' => 'Cliente que tiene cuenta de usuario en el sistema',
                'published' => 0,
            ),

            array(
                'id' => 7,
                'tipo' => 'Cliente sin Registro',
                'descripcion' => 'Clientes que no tienen registro',
                'published' => 0,
            ),

        ));
		DB::table('users')->insert(
                    
            array(
                'id' => 1,
                'nombre' => 'Administrador',
                'ap' => '',
                'am' => '',
                'genero' => 'M',
                'email' => 'c.torres@bitweb.mx',
                'direccion' => '',
                'username' => 'admin',
                'password' => '$2y$10$Rchl13FHSvYzNaqZhURWm.XntT20LHmsHKPYxhZzfNTgjGHS5Nrja',
                'random_key' => '',
                'nivel_id' => 1,
                'status' => 'A',
                'remember_token' => '',
                'created_at' => '2014-07-01 17:52:17',
                'updated_at' => '2014-07-01 17:52:17',
                'agree' => 0,
            )

        );
    }
}